#pragma once

//Adapted from https://github.com/rsta2/circle/blob/master/lib/bcmpciehostbridge.cpp

#define MEM_PCIE_RANGE_START    0x600000000ULL
#define MEM_PCIE_RANGE_SIZE		0x4000000ULL

#define MEM_PCIE_RANGE_PCIE_START	    0xF8000000ULL		
#define MEM_PCIE_RANGE_START_VIRTUAL	0xFA000000UL
#define MEM_PCIE_RANGE_END_VIRTUAL	    (MEM_PCIE_RANGE_START_VIRTUAL + 2 * MEGABYTE - 1ULL)

#define MEM_PCIE_DMA_RANGE_START	0ULL
#define MEM_PCIE_DMA_RANGE_SIZE		0x100000000ULL
#define MEM_PCIE_DMA_RANGE_PCIE_START	0ULL			

#define PCIE_MSI_INTR2_CLR				0x4508
#define PCIE_MSI_INTR2_MASK_SET         0x4510

#define  STATUS_PCIE_DL_ACTIVE_MASK     0x20
#define  STATUS_PCIE_DL_ACTIVE_SHIFT	5
#define  STATUS_PCIE_PHYLINKUP_MASK		0x10
#define  STATUS_PCIE_PHYLINKUP_SHIFT	4

#define PCIE_STATUS                                             0x4068

#define PCIE_MISC_MISC_CTRL                                     0x4008

#define PCIE_MISC_MISC_CTRL_MAX_BURST_SIZE_MASK			0x300000
#define PCIE_MISC_MISC_CTRL_MAX_BURST_SIZE_SHIFT		0x14
#define PCIE_MISC_MISC_CTRL_SCB0_SIZE_MASK			    0xf8000000
#define PCIE_MISC_MISC_CTRL_SCB0_SIZE_SHIFT			    0x1b
#define PCIE_MISC_MISC_CTRL_SCB1_SIZE_MASK			    0x7c00000
#define PCIE_MISC_MISC_CTRL_SCB1_SIZE_SHIFT			    0x16
#define PCIE_MISC_MISC_CTRL_SCB2_SIZE_MASK			    0x1f
#define PCIE_MISC_MISC_CTRL_SCB2_SIZE_SHIFT			    0x0
#define PCIE_MISC_MISC_CTRL_CFG_READ_UR_MODE_MASK		0x2000
#define PCIE_MISC_MISC_CTRL_CFG_READ_UR_MODE_SHIFT		0xd

#define PCIE_MISC_HARD_PCIE_HARD_DEBUG                          0x4304
#define PCIE_MISC_HARD_PCIE_HARD_DEBUG_SERDES_IDDQ_MASK         0x08000000
#define PCIE_MISC_HARD_PCIE_HARD_DEBUG_SERDES_IDDQ_SHIFT        0x1b
#define PCIE_MISC_HARD_PCIE_HARD_DEBUG_CLKREQ_L1SS_ENABLE_MASK  0x200000
#define PCIE_MISC_HARD_PCIE_HARD_DEBUG_CLKREQ_DEBUG_ENABLE_MASK 0x2
#define PCIE_MISC_HARD_PCIE_HARD_DEBUG_CLKREQ_DEBUG_ENABLE_SHIFT 0x1

#define PCIE_RGR1_SW_INIT_1                                    0x9210
#define PCIE_RGR1_SW_INIT_1_INIT_MASK                           0x2
#define PCIE_RGR1_SW_INIT_1_INIT_SHIFT                          0x1
#define PCIE_RGR1_SW_INIT_1_PERST_MASK                          0x1
#define PCIE_RGR1_SW_INIT_1_PERST_SHIFT                         0x0

#define BURST_SIZE_128			0
#define BURST_SIZE_256			1
#define BURST_SIZE_512			2

#define PCIE_MISC_RC_BAR1_CONFIG_LO			0x402c
#define PCIE_MISC_RC_BAR1_CONFIG_HI			0x4030
#define PCIE_MISC_RC_BAR2_CONFIG_LO			0x4034
#define PCIE_MISC_RC_BAR2_CONFIG_HI			0x4038
#define PCIE_MISC_RC_BAR3_CONFIG_LO			0x403c
#define PCIE_MISC_MSI_BAR_CONFIG_LO			0x4044
#define PCIE_MISC_MSI_BAR_CONFIG_HI			0x4048

#define PCIE_MISC_RC_BAR1_CONFIG_LO_SIZE_MASK			0x1f
#define PCIE_MISC_RC_BAR1_CONFIG_LO_SIZE_SHIFT			0x0
#define PCIE_MISC_RC_BAR2_CONFIG_LO_SIZE_MASK			0x1f
#define PCIE_MISC_RC_BAR2_CONFIG_LO_SIZE_SHIFT			0x0
#define PCIE_MISC_RC_BAR3_CONFIG_LO_SIZE_MASK			0x1f
#define PCIE_MISC_RC_BAR3_CONFIG_LO_SIZE_SHIFT			0x0

#define PCIE_INTR2_CPU_BASE				0x4300
#define STATUS				0x0
#define SET				0x4
#define CLR				0x8


#define PCI_EXP_LNKCAP_SLS	        0x0000000f
#define PCI_EXP_LNKCAP_SLS_2_5GB    0x00000001
#define PCI_EXP_LNKCAP_SLS_5_0GB    0x00000002
#define PCI_EXP_LNKCAP_SLS_8_0GB    0x00000003
#define PCI_EXP_LNKCAP_SLS_16_0GB   0x00000004
#define BRCM_PCIE_CAP_REGS			0x00a
#define PCIE_GEN	                2
#define PCI_EXP_LNKCAP		        12
#define PCI_EXP_LNKCTL2		        48
#define PCI_EXP_LNKCTL2_TLS		    0x000
#define PCI_EXP_LNKCTL2_TLS_2_5GT	0x0001
#define PCI_EXP_LNKCTL2_TLS_5_0GT	0x0002
#define PCI_EXP_LNKCTL2_TLS_8_0GT	0x0003
#define PCI_EXP_LNKCTL2_TLS_16_0GT	0x0004

#define PCIE_MISC_MISC_CTRL_SCB_ACCESS_EN_MASK			0x1000
#define PCIE_MISC_MISC_CTRL_SCB_ACCESS_EN_SHIFT			0xc

#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LO		0x400c
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_HI		0x4010
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT_LIMIT_MASK	0xfff00000
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT_LIMIT_SHIFT	0x14
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT_BASE_MASK	0xfff0
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT_BASE_SHIFT	0x4
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT_NUM_MASK_BITS	0xc
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_HI_BASE_MASK		0xff
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_HI_BASE_SHIFT	0x0
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LIMIT_HI_LIMIT_MASK	0xff
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LIMIT_HI_LIMIT_SHIFT	0x0

#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT	0x4070
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_HI		0x4080
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LIMIT_HI		0x4084

#define PCI_EXP_LNKSTA		18	/* Link Status */
#define  PCI_EXP_LNKSTA_CLS	0x000f	/* Current Link Speed */
#define  PCI_EXP_LNKSTA_CLS_2_5GB 0x0001 /* Current Link Speed 2.5GT/s */
#define  PCI_EXP_LNKSTA_CLS_5_0GB 0x0002 /* Current Link Speed 5.0GT/s */
#define  PCI_EXP_LNKSTA_CLS_8_0GB 0x0003 /* Current Link Speed 8.0GT/s */
#define  PCI_EXP_LNKSTA_CLS_16_0GB 0x0004 /* Current Link Speed 16.0GT/s */
#define  PCI_EXP_LNKSTA_NLW	0x03f0	/* Negotiated Link Width */
#define  PCI_EXP_LNKSTA_NLW_X1	0x0010	/* Current Link Width x1 */
#define  PCI_EXP_LNKSTA_NLW_X2	0x0020	/* Current Link Width x2 */
#define  PCI_EXP_LNKSTA_NLW_X4	0x0040	/* Current Link Width x4 */
#define  PCI_EXP_LNKSTA_NLW_X8	0x0080	/* Current Link Width x8 */
#define  PCI_EXP_LNKSTA_NLW_SHIFT 4	/* start of NLW mask in link status */
#define  PCI_EXP_LNKSTA_LT	0x0800	/* Link Training */
#define  PCI_EXP_LNKSTA_SLC	0x1000	/* Slot Clock Configuration */
#define  PCI_EXP_LNKSTA_DLLLA	0x2000	/* Data Link Layer Link Active */
#define  PCI_EXP_LNKSTA_LBMS	0x4000	/* Link Bandwidth Management Status */
#define  PCI_EXP_LNKSTA_LABS	0x8000	/* Link Autonomous Bandwidth Status */

#define PCIE_RC_CFG_VENDOR_VENDOR_SPECIFIC_REG1		0x0188
#define PCIE_RC_CFG_VENDOR_VENDOR_SPECIFIC_REG1_ENDIAN_MODE_BAR2_MASK	0xc
#define PCIE_RC_CFG_VENDOR_VENDOR_SPECIFIC_REG1_ENDIAN_MODE_BAR2_SHIFT	0x2

#define PCIE_RC_CFG_PRIV1_ID_VAL3			0x043c
#define PCIE_RC_CFG_PRIV1_ID_VAL3_CLASS_CODE_MASK		0xffffff
#define PCIE_RC_CFG_PRIV1_ID_VAL3_CLASS_CODE_SHIFT		0x0

#define PCIE_MISC_PCIE_STATUS				0x4068

#define PCIE_MISC_PCIE_STATUS_PCIE_PORT_MASK			0x80
#define PCIE_MISC_PCIE_STATUS_PCIE_PORT_SHIFT			0x7

#define lo32(addr) addr & UINT32_MAX
#define hi32(addr) (addr >> 32) & UINT32_MAX